name: Build and Publish

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # Set up Emscripten
    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14

    # Build your project with CMake
    - name: Build
      run: |
        npm run build

    # Publish to GitHub Packages (adjust for your packaging tool)
    - name: Publish
      run: |
        # Assuming you're generating a npm package
        npm publish
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
